name: Build and Upload Executables

on:
  push:
    branches: [grafica_clusters]
  pull_request:
    branches: [grafica_clusters]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Build binaries
        run: make -C ProyectoIntermedioISHPC -j

      - name: Upload executables
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: ProyectoIntermedioISHPC/bin/*.x
