name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ProyectoIntermedioISHPC

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make catch2

      - name: Stub spack command
        run: |
          mkdir -p $HOME/bin
          cat > $HOME/bin/spack << 'EOF'
          #!/usr/bin/env bash
          # no-op stub so “spack load” always succeeds
          exit 0
          EOF
          chmod +x $HOME/bin/spack
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Build & test
        run: make test
